Updated

diff --git a/scripts/airoscript-ng/src/functions/_internal b/scripts/airoscript-ng/src/functions/_internal
--- a/scripts/airoscript-ng/src/functions/_internal
+++ b/scripts/airoscript-ng/src/functions/_internal
@@ -16,18 +16,26 @@
 #        along with this program; if not, write to the Free Software
 #        Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
+required(){
+	check_function $1 ||  { specialwarn "${warn}${2}"; return 1; }
+}
+
 error(){
     export ERRORS="$@";
 }
+info(){
+    export INFOS="$@";
+}
+
 
 reload_config(){
-#    _source "./airoscript-ng.conf.devel ~/.airoscript-ng/airoscript-ng.conf /etc/airoscript-ng.conf /usr/local/etc/airoscript-ng.conf"
-#    _source "./airoscript-ng_advanced.conf.devel ~/.airoscript-ng_advanced/airoscript-ng_advanced.conf /etc/airoscript-ng_advanced.conf /usr/local/etc/airoscript-ng_advanced.conf"
-return
+	return
 }
 
 cleanautovars(){
-    export AUTO=0; export QUIET=""; export INTERACTIVE=$OLDINTERACTIVE
+    export AUTO=0; 
+	export QUIET=""; 
+	export INTERACTIVE=$OLDINTERACTIVE
     return
 }
 
@@ -61,7 +69,7 @@ Usage: $(basename $0) [-h] [-t TERMINAL] [-v] [-w WIRELESS_CARD] [-b] [-m fakema
 
 options:
    -h                    Show this message
-   -t [xterm|screen]     Specify terminal
+   -t TERMINAL           Specify terminal
    -c                    Launches an interface selection menu (requires -pzenity)
    -v                    Verbose & debug mode
    -w wireless_card      Specify wifi card
@@ -77,13 +85,13 @@ eof
 }
 
 launch_help_fifo(){
-    mkfifo $DUMP_PATH/help_fifo
-    xterm -e "tail -f $DUMP_PATH/help_fifo"
+    [[ -e $DUMP_PATH/help_fifo ]] || mkfifo $DUMP_PATH/help_fifo &>/dev/null
+	execute "Help"  "tail -f $DUMP_PATH/help_fifo"
 }
 
 help_fifo(){
-    clear > $DUMP_PATH/help_fifo
-    echo $@ > $DUMP_PATH/help_fifo
+    clear >> $DUMP_PATH/help_fifo
+    echo -e $@ >> $DUMP_PATH/help_fifo
 }
 
 function choose_interface(){
@@ -112,7 +120,6 @@ setargs(){
     for i in ${opt_functions[@]}; do [[ $i == "usage" ]] && { usage; exit 1; }; done # Small hack to execute usage the first 
     for i in ${opt_functions[@]}; do [[ $i != auto ]] && options_$i || execute_auto=1; done
     [[ $execute_auto ]] && options_auto; # Small hack to execute auto the lastest xD
-    [[ $TERMINAL == "screen" ]] && screen_startup ${@}
 }
 
 options_m(){ opts_change_$opts_mac_opt; }
@@ -149,8 +156,7 @@ load_plugins(){
 }
 
 initial_warning(){
-	warn -en $mark;
-    _ "  Airoscript is provided under the gpl.
+    markwarn $"  Airoscript is provided under the gpl.
 I'm not responsible of the use anyone can give to airoscript.
 Written for educational purpose in mind.
 "
@@ -159,9 +165,12 @@ sleep $warn_time
 
 # Standard functions.
 
+markwarn(){
+	echo -e "${warn}${@}"
+}
 
 _debug(){
-    if [ "$debug" == 1 ]; then echo -en $mark; _ $1; fi
+    if [ "$debug" == 1 ]; then markwarn $1; fi
 }
 
 execute(){ 
@@ -172,28 +181,25 @@ execute(){
     if [  "$ADDOPTIONS" != "" ]; then
         printf -- "Executing $@"
         echo
-        read -p "Enter extra options to execute: " eopts
+        read -p $"Enter extra options to execute: " eopts
     fi
-    if [ $TERMINAL == "screen" ]; then
-		$CDCMD screen -S airoscript -c $SCREENRC -D -RR -X screen -t $title
-		$CDCMD screen -S airoscript -c $SCREENRC -X at "*" eval "stuff \"${@} $eopts; exit\"\015" 
-    else
-        if [ "$1" == "crack" ]; then HOLDA="-hold"; shift; fi # FIXME This will work just on xterm.
+        if [ "$1" == "crack" ]; then shift; fi # FIXME This will not do anything. 
         if [ "$QUIET" != "" ] || [ "$AUTO" == "1" ]; then 
             [[ $NOTITLE ]] || warn "${mark}$title"
-            if [[ $wait_for_execute ]]; then
-                ${@} $eopts &> /dev/null
-            else
+            if [[ $wait_for_execute != 1 ]]; then
                 ${@} $eopts &> /dev/null &
+            else
+                ${@} $eopts &> /dev/null
             fi
         else
-            [[ $wait_for_execute == 1 ]] && {
-                $CDCMD $TERMINAL $HOLDA $TITLEFLAG "$title" $TOPLEFTBIG $BGC $BACKGROUND_COLOR $FGC $DUMPING_COLOR $EXECFLAG "${@} $eopts"
+			args="${@}"; args="${args/% /} ${eopts}" # Failsafe, this way if there's a trailing space it'll remove it before executing.
+            [[ $wait_for_execute != 1 ]] && {
+                $CDCMD $TERMINAL $HOLDA $TITLEFLAG "$title" $termargs  "$args" &
             } || {
-                $CDCMD $TERMINAL $HOLDA $TITLEFLAG "$title" $TOPLEFTBIG $BGC $BACKGROUND_COLOR $FGC $DUMPING_COLOR $EXECFLAG "${@} $eopts" &
+                $CDCMD $TERMINAL $HOLDA $TITLEFLAG "$title" $termargs "$args"
             }
         fi
-    fi 
+	[[ $debug == 1 ]] && { echo $TERMINAL $HOLDA $TITLEFLAG "$title" $TOPLEFTBIG $BGC $BACKGROUND_COLOR $FGC $DUMPING_COLOR $EXECFLAG "$args"; read; }
     save_pids $!
 }
 
@@ -202,7 +208,7 @@ monmode(){ { ifconfig $1 up; $iwconfig $1 |grep "Monitor" && if [ $? != 0 ]; the
 # this function allows debugging, called from main menu.
 function debug {
 	if [ "$debug" == "1" ] || [ "$hold" == "1"  ]; then
-		export HOLD=$HOLDFLAG; _ "Debug Mode enabled, you'll have to manually close windows"
+		export HOLD=$HOLDFLAG; echo $"Debug Mode enabled, you'll have to manually close windows"
 	else export HOLD="" ;fi
 }
 
@@ -215,10 +221,10 @@ _read(){
 checkdir(){
     if [ -d $DUMP_PATH ]; then
         if [ "$DEBUG" == 1 ]; then
-            _ "[INFO] Output folder is" " $DUMP_PATH";
+            echo $"[INFO] Output folder is" " $DUMP_PATH";
         fi
     else
-        _ "[Error] Output folder does not exists or is a regular file."
+        echo $"[Error] Output folder does not exists or is a regular file."
         exit
     fi
 }
@@ -241,11 +247,7 @@ attack_wep(){
 }
 
 attack_opn(){ # If no encryption detected
-    if [ "$Host_SSID" = "" ]; then
-        $clear &&  echo  "`gettext 'ERROR: You have to select a target'`"
-    else
-        $clear && echo `gettext "ERROR: Network not encrypted or no network selected "`
-    fi
+	$clear && error "Network not encrypted or not network selected";
 }
 
 capture(){
@@ -259,6 +261,7 @@ tag(){ echo -ne "\t"; }
 hardclean(){ rm -rf $DUMP_PATH/$Host_MAC*; }
 
 single_question(){ read -p "${@}" ans; }
+special_single_question(){ single_question "${@}"; }
 warn(){ echo "${@}"; }
 specialwarn(){ echo -e -n "${@}"; }
 yesno(){
@@ -267,7 +270,9 @@ yesno(){
 }
 
 check_default_software(){
-	return 0
+	for program in ${required_software[@]}; do
+		[[ $(whereis $program) ]] || { echo -en "$program"; warn "not found, quitting." ; exit ; } 
+	done
 }
 
 _source $path/internal/startup
